artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/nasserml/Branching/raw/main/Rice_Images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5




prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

processed_data:
  root_dir: artifacts/processed_data
  train_dir: artifacts/processed_data/train
  processed_train_data_pickle_file: artifacts/processed_data/train/processed_train_data.pkl
  valid_dir: artifacts/processed_data/valid
  processed_valid_data_pickle_file: artifacts/processed_data/valid/processed_valid_data.pkl
  test_dir: artifacts/processed_data/test
  processed_test_data_pickle_file: artifacts/processed_data/test/processed_test_data.pkl



training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5